name: Challenge Module - Test check

# Run tests for PRs
on:
  pull_request:
    branches:
      - develop # If you have a develop branch before main branch
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['8.0']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: install dependencies
        run: npm install
      - name: Start MongoDB Test Realm
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Cypress run E2E
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start
      - name: Cypress run components
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start
          component: true
        

